monolog:
    handlers:
        ignore_failures:
            type: whatfailuregroup
            members: [gelf_fingers_crossed]
        gelf_fingers_crossed:
            type:          fingers_crossed
            action_level:  warning
            handler:       gelf
        gelf:
            type:   gelf
            publisher:
                hostname: "%xeonys.elk.gelf.host%"
                port:     "%xeonys.elk.gelf.port%"
            level: debug
